services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - job_workers_net
    environment:
      REDIS_PASSWORD: password
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL,CONFIG,KEYS,EVAL

  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - job_workers_net
    depends_on:
      - redis
    environment:
      REDIS_ADDRESS: redis:6379
      REDIS_PASSWORD: password 
      REDIS_DB: 0
      REDIS_QUEUE_NAME: jobs
      REDIS_JOB_STATUS_TTL_SECONDS: 604800

volumes:
  redis_data:

networks:
  job_workers_net: